### ISSUE TITLE
 Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by Sadovikow** [wesbos/keycodes#257] opened 2018-10-25 09:58 UTC
Hello! Error on https://keycode.info/

scripts.js?v=10112018:190 Uncaught TypeError: Cannot read property 'appendChild' of null
    at scripts.js?v=10112018:190

**Comment by palashmon** [comment] 2018-10-25 13:00
Hi, which browser did you tested this on?

**Comment by Sadovikow** [comment] 2018-10-25 13:08
Chrome

**Comment by palashmon** [comment] 2020-11-07 05:42
Not able to reproduce the issue. Closing this for now. Please re-open if needed.

**Closed by palashmon** 2020-11-07 05:42 UTC
