### ISSUE TITLE
Keyboard combination like `shift + button`

### ISSUE THREAD

**Issue by theasder** [wesbos/keycodes#15] opened 2015-05-06 14:15 UTC
It would be great to add case sensitivity or special characters to your service, for instance. Thank you.

**Comment by Mazuh** [comment] 2015-10-13 03:55
I think this isn't what the service should do. You see, repo is called "keycodes" cause it brings to you the keyCode property, very useful for web developers in some situations, However, you're asking for character codes (case sensitive, special chars and so on). According to W3C (http://www.w3schools.com/jsref/event_key_keycode.asp):

>>The difference between the two code types:
>>   * Character codes - A number which represents an ASCII character
>>   * Key codes - A number which represents an actual key on the keyboard

It's more useful and (I should say) ordinary for devs to know which key is being pressed no matter what modifier is being pressed too. For example: when you're pressing W key in your keyboard, I do not care what else is being pressed, cause W key will be always... the W key! When a developer wants to know what text was (or should be) printed after key down, there are other properties and a lot of algorithms.

**Comment by wesbos** [comment] 2015-11-23 14:16
This would be nice to have - going to figure out regional keyboard support first though.

**Comment by wesbos** [comment] 2018-10-02 21:03
dupe of another issue -will come :)

**Closed by wesbos** 2018-10-02 21:03 UTC
Labels: enhancement, help wanted
